name: deployment

on:
  push:
    branches:
      - au_restaurant_prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{secrets.AURESTAURANT_HEROKU_API_KEY}}
          heroku_app_name: "aurestaurant"
          heroku_email: ${{secrets.AURESTAURANT_HEROKU_EMAIL}}
          usedocker: true
